### ISSUE TITLE
NAs introduced by coercion

### ISSUE THREAD

**Issue by mihainiculita** [ECCC-CDAS/RClimDex#2]
Hello,

I get the following error when I try to un the calculation:

Error in ParseError("[[:alnum:]_.:/\b\\-]*", as.character(tclvalue(rclimdex.env$entries.file.in)),  : 
  (converted from warning) NAs introduced by coercion

Any idea why?

Thank you!

**Comment by rodneychan-ec** [comment]
There was an compatibility issue with R 3.5.1, should be fixed in new release (1.9-3) now. Otherwise 1.9-2 have to use R 3.3.3 or lower.
